### ISSUE TITLE
How to compile the supervisor

### ISSUE THREAD

**Issue by xhalo32** [home-assistant/hassio-builder#28]
I've been bashing my head against the wall for a few hours now and can't seem to figure out how to build the [supervisor image](https://hub.docker.com/r/homeassistant/amd64-hassio-supervisor) for local development.

The [development guide](https://github.com/home-assistant/hassio/#development) doesn't have any docker related info...

Any help for getting the development environment setup with docker is greatly appreciated!

**Comment by pvizeli** [comment]
use vscode

**Comment by xhalo32** [comment]
Thanks for your quick response!
No, I won't use vscode. So how do I get the development environment set up from the command line?
